### ISSUE TITLE
実装のリポジトリでgithub actionsでdocker imageをリリースするようにする

### ISSUE THREAD

**Issue by TMats** [matsuolab/roomba_hack#23]

**Comment by Jumpei-Arima** [comment]
以下のworkflowを作成。
https://github.com/matsuolab/roomba_hack/blob/master/.github/workflows/docker-publish.yml

ghcrのlogin userとして @TMats を指定しているので、repoのsecretsにCR_PATを登録していただけばと思います。
(weblab_hsr_tidyupと運用は同じです。)

**Comment by TMats** [comment]
ありがとうございます，CR_PATの設定はしたんですが，ubuntuの方のイメージのビルドがこけてしまってるっぽいですね
https://github.com/matsuolab/roomba_hack/runs/8167846605?check_suite_focus=true
（あとコンテナにpushするのってmasterだけにしますか．．．？それとも全部pushされた方がいいんですかね（自分は前者でもいいような気がします

**Comment by Jumpei-Arima** [comment]
ビルドこけてたのは、ignitionまわりのインストール中に何故か404 not foundが出てたからですね。re-runしたらうまく行きました。 

以下で、pushするのは、masterにpushされた時だけのはずです(PRはtest(buildできるか)だけ実施)。
https://github.com/matsuolab/roomba_hack/blob/master/.github/workflows/docker-publish.yml#L4-L9

**Comment by TMats** [comment]
あ，すみません見落としていました

ビルドできましたね，releaseに反映されるようになりました．ありがとうございます

<img width="338" alt="image" src="https://user-images.githubusercontent.com/16148653/188274725-a6b1f576-1a5e-49eb-b05c-8d2b6340cce5.png">
